# CircleCI 2.1 configuration file
version: 2.1

references:
  workspace_root: &workspace_root "/home/circleci/workspace"

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  api:
    type: boolean
    default: false
  app:
    type: boolean
    default: false
  image:
    type: boolean
    default: false
  mailing:
    type: boolean
    default: false
  ui:
    type: boolean
    default: false

executors:
  openjdk-docker:
    docker:
      - image: circleci/openjdk:8u212-stretch
      - image: circleci/mysql:5.7
  ubuntu-machine:
    machine: 
      image: ubuntu-1604:201903-01

jobs:
  trigger-workflows:
    executor: openjdk-docker
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: openjdk-docker
    working_directory: *workspace_root/<< parameters.package_name >>

    steps:
      - checkout:
          path: *workspace_root
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: openjdk-docker
    working_directory: *workspace_root/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: *workspace_root
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_name: api
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app:
    when: << pipeline.parameters.app >>
    jobs:
      - build:
          name: app-build
          package_name: app
      - deploy:
          name: app-deploy
          package_name: app
          requires:
            - app-build

  image:
    when: << pipeline.parameters.image >>
    jobs:
      - build:
          name: image-build
          package_name: image
      - deploy:
          name: image-deploy
          package_name: image
          requires:
            - image-build

  mailing:
    when: << pipeline.parameters.mailing >>
    jobs:
      - build:
          name: mailing-build
          package_name: mailing
      - deploy:
          name: mailing-deploy
          package_name: mailing
          requires:
            - mailing-build

  ui:
    when: << pipeline.parameters.ui >>
    jobs:
      - build:
          name: ui-build
          package_name: ui
      - deploy:
          name: ui-deploy
          package_name: ui
          requires:
            - ui-build